### ISSUE TITLE
Tracking issue for documented errors in effector-react

### ISSUE THREAD

**Issue by sergeysova** [effector/effector#710]
- [ ] Add page about `expect useStore argument to be a store` error
- [ ] Add page about `expect useUnit argument to be a unit` error
- [ ] Add page about `useStoreMap expects a store` error
- [ ] Add page about `useStoreMap expects an array as keys` error
- [ ] Add page about `useStoreMap expects a function` error
- [ ] Add page about `expect useList first argument to be a store` error
- [ ] Add page about `expect useList's renderItem to be a function` error
- [ ] Add page about `expect useList's keys to be an array` error
- [ ] Add page about `shape should be a store or object with stores` error
- [ ] Add page about `createContextComponent is deprecated` deprecation
- [ ] Add page about `createReactState is deprecated` deprecation
- [ ] Add page about `No scope found, consider adding <Provider> to app root` error
- [ ] Add page about `not implemented` error
- [ ] Add page about `createReactState is deprecated` deprecation

Related #690

**Comment by maroon775** [comment]
Up
