### ISSUE TITLE
Tracking issue for documented errors in forest

### ISSUE THREAD

**Issue by sergeysova** [effector/effector#711]
- [ ] Add page about `called outside from using() closure` error
- [ ] Add page about `incorrect parent` error
- [ ] Add page about `unexpected draft type` warning
- [ ] Add page about `unexpected currentTemplate type` warning
- [ ] Add page about `"handler" extension can be used only with element nodes` error
- [ ] Add page about `handler for should be event` error
- [ ] Add page about `node() hook supported only in h() nodes` warning
- [ ] Add page about `your environment has no document` error
- [ ] Add page about `using() argument is missing` error
- [ ] Add page about `variant({source}) should be unit` error
