### ISSUE TITLE
effector Spacewatch 23 tracking issue

### ISSUE THREAD

**Issue by sergeysova** [effector/effector#755]
- [x] Remove flow typings from this repo #912
- [x] Remove deprecated options and methods
	- [x] Call of derived event #905
	- [x] Unit call from pure function #905
	- [x] #846
	- [x] #843 
	- [x] #842
	- [x] #845
	- [x] #844
	- [x] Remove `createStoreObject` #908
	- [x] #1018
- [x] Introduce new types
	- [x] Introduce `EventCallable<T>` and `StoreWritable<T>`. #847 (#966) 
	- [x] Forbid derived units in operators `target`s
- [x] Deprecate some features
	- [x] `forward` and `guard` #913
	- [x] Rename `greedy` into `batch` in `sample` (#972)
		- [x] Deprecate `greedy: false`, introduce `batch: true`
	- [x] #848
   - [x] Remove fork(scope)-related code (activeEffects, etc)
	- [x] Deprecate `reactSsr` option in babel-plugin (#910)
	- [ ] Deprecate `bindings` option in swc plugin (@Drevoed) https://github.com/effector/swc-plugin/#bindings
	- [x] Deprecate onlyChanges option in serialize #907
	- [x] Deprecate `{[fx.sid]: Function}` in fork handlers (#973)
	- [x] Deprecate `.watch(trigger, watcher)` #906
	- [x] Deprecate `getType()` (#899)
	- [x] Deprecate `effector/babel-plugin-react` #948
	- [x] Deprecate `fork(domain)` (https://github.com/effector/effector/pull/950)
	- [x] Deprecate `hydrate(domain)` (https://github.com/effector/effector/pull/950)
	- [x] Deprecate `hydrate(fork(domain))` — hydrating scope forked from domain (https://github.com/effector/effector/pull/950)
- [x] #903
- [x] https://github.com/effector/effector/issues/633 (#849)
- [x] https://github.com/effector/effector/issues/535 (#909)
- [x] Unify programmatic sid insertions: `sample({and: arg, or: {sid, name})` vs `restore(arg, arg, {sid, name})` (#969)
- [x] Throw an exception if `fn` in `$store.map(fn)` returns `undefined` in the initialization
      (#828)
- [x] Replace `createWatch` from the internal `effector-react` impl with `createWatch` from the `effector` package (related: https://github.com/effector/effector/pull/646) (#850)
- [x] Add `batch` option to `createWatch` (#850)
- [x] https://github.com/effector/effector/issues/829 (#895)
- [x] Fix duplicated combine calls https://github.com/effector/effector/pull/916
- [x] Fix reading obsolete source value in attach (#1011)
- [x] https://github.com/effector/effector/issues/863
- [x] Add `@withease/factories` to babel defaults (#995)
- [x] Add custom handling for `patronum/{method}` imports (#996)
- [x] Show warning when returns undefined in stores
	- [x] #920
- [x] Bindings
	- [x] https://github.com/effector/effector/issues/768
	- [x] #872
	- [x] #874
	- [x] #873
	- [x] https://github.com/effector/effector/issues/767
	- [x] [`$watchAsStore` and `$store` in `effector-vue`](https://github.com/effector/effector/pull/1004)
	- [x] https://github.com/effector/effector/issues/919
	- [x] Deprecate effector-react's `useStore/useEvent` in favor of `useUnit` (https://github.com/effector/effector/pull/951)
	- [x] https://github.com/effector/effector/pull/1003

- [x] 10% performance improve (#1014)
- [x] Improve error messages, now when validation error happened, it will show unit name and other relevant information in message (#1015)

Nice to have:
- Improve message in sample validation in case of array in target like "expect item _at index 3_ of target  to be _non-derived_ unit"
---

**Ecosystem updates:**

- [ ] https://github.com/effector/reflect/issues/44
- [x] https://github.com/effector/patronum/issues/175
- [ ] https://github.com/effector/swc-plugin/issues/29
- [ ] https://github.com/effector/eslint-plugin/issues/134
- [ ] https://github.com/effector/vite-react-template/issues/13
- [ ] https://github.com/effector/logger/issues/116
- [ ] https://github.com/effector/inspector/issues/64
- [ ] https://github.com/effector/repl/issues/31

---

**How to release:**

- [ ] Create a changelog in releases and CHANGELOG.md
- [ ] Create a migration guide
- [ ] Update the reference documentation of the all touched methods
- [ ] Write article in [community.effector.dev](https://community.effector.dev/core)
- [ ] Create a new image banner
- [ ] Publish into Telegram channel
- [ ] Tweet it with the most interesting picks
- [ ] Publish in Discord Announcements
- [ ] Move documentation for 22.x.x to https://v22.effector.dev
	- [ ] Add link to v22 to all other versions of docs
